const items = [
  {
    id: 1,
    name: "iPhone 14 128GB",
    brand: "Apple",
    price: 879,
    rating: 4.9,
    image: "/assets/products/iphone/iphone1.jpeg",
    img1: "/assets/products/iphone/iphone2.webp",
    img2: "/assets/products/iphone/iphone3.webp",
    img3: "/assets/products/iphone/iphone4.webp",
    img4: "/assets/products/iphone/iphone5.webp",
    url: "/products/1",
    account: 9963161088,
    bankId: "648f942a45ca153a0334a232",
    category: "Phone",
  },
  {
    id: 2,
    name: "Beats Studio3 Wireless Headphones",
    brand: "Beats",
    price: 220,
    rating: 4.8,
    image: "/assets/products/beats/b1.webp",
    img1: "/assets/products/beats/b2.webp",
    img2: "/assets/products/beats/b3.webp",
    img3: "/assets/products/beats/b4.webp",
    img4: "/assets/products/beats/b1.webp",
    url: "/products/2",
    account: 5434753524,
    bankId: "6492c2b3fe0dd1f5e9aca9b9",
    category: "Headphones",
  },
  {
    id: 3,
    name: 'ASUS Vivobook 17.3" Full HD PC Laptop',
    brand: "Apple",
    price: 399,
    rating: 4.7,
    image: "/assets/products/vivobook/vivo1.webp",
    img1: "/assets/products/vivobook/vivo2.webp",
    img2: "/assets/products/vivobook/vivo3.webp",
    img3: "/assets/products/vivobook/vivo4.webp",
    img4: "/assets/products/vivobook/vivo5.webp",
    url: "/products/3",
    account: 9963161088,
    bankId: "648f942a45ca153a0334a232",
    category: "Laptop",
  },
  {
    id: 4,
    name: "OnePlus 9 Pro 5G 256GB",
    brand: "OnePlus",
    price: 999,
    rating: 4.9,
    image: "/assets/products/oneplus/oneplus1.webp",
    img1: "/assets/products/oneplus/oneplus1.webp",
    img2: "/assets/products/oneplus/oneplus2.webp",
    img3: "/assets/products/oneplus/oneplus3.png",
    img4: "/assets/products/oneplus/oneplus2.webp",
    url: "/products/4",
    account: 2890218458,
    bankId: "6492c319fe0dd1f5e9aca9be",
    category: "Phone",
  },
  {
    id: 5,
    name: "Beats Studio Buds",
    brand: "Beats",
    price: 165,
    rating: 4.8,
    image: "/assets/products/beats-buds/b1.webp",
    img1: "/assets/products/beats-buds/b2.webp",
    img2: "/assets/products/beats-buds/b3.webp",
    img3: "/assets/products/beats-buds/b4.webp",
    img4: "/assets/products/beats-buds/b1.webp",
    url: "/products/5",
    account: 5434753524,
    bankId: "6492c2b3fe0dd1f5e9aca9b9",
    category: "Headphones",
  },
  {
    id: 6,
    name: 'Apple MacBook Air 13.3" Laptop',
    brand: "Apple",
    price: 899,
    rating: 4.7,
    image: "/assets/products/macbook/mac1.webp",
    img1: "/assets/products/macbook/mac2.webp",
    img2: "/assets/products/macbook/mac3.webp",
    img3: "/assets/products/macbook/mac4.webp",
    img4: "/assets/products/macbook/mac1.webp",
    url: "/products/6",
    account: 9963161088,
    bankId: "648f942a45ca153a0334a232",
    category: "Laptop",
  },
  {
    id: 7,
    name: "Google Pixel 5",
    brand: "Google",
    price: 350,
    rating: 4.9,
    image: "/assets/products/pixel/pixel1.webp",
    img1: "/assets/products/pixel/pixel2.webp",
    img2: "/assets/products/pixel/pixel3.webp",
    img3: "/assets/products/pixel/pixel4.jpeg",
    img4: "/assets/products/pixel/pixel5.jpeg",
    url: "/products/7",
    account: 5448451675,
    bankId: "6492c231fe0dd1f5e9aca9b4",
    category: "Phone",
  },
  {
    id: 8,
    name: "Razer kraken V3 X Wired Gaming Headset",
    brand: "Razer",
    price: 45,
    rating: 4.8,
    image: "/assets/products/razer/r1.webp",
    img1: "/assets/products/razer/r2.webp",
    img2: "/assets/products/razer/r3.webp",
    img3: "/assets/products/razer/r4.webp",
    img4: "/assets/products/razer/r5.webp",
    url: "/products/8",
    account: 8593460290,
    bankId: "6492bdadfb7efdebf2c5d802",
    category: "Headphones",
  },
  {
    id: 9,
    name: 'ASUS TUF Gaming 17.3" 144Hz FHD',
    brand: "Asus",
    price: 1250,
    rating: 4.7,
    image: "/assets/products/tuf/tuf1.webp",
    img1: "/assets/products/tuf/tuf2.webp",
    img2: "/assets/products/tuf/tuf3.webp",
    img3: "/assets/products/tuf/tuf4.webp",
    img4: "/assets/products/tuf/tuf5.jpeg",
    url: "/products/9",
    account: 7020683959,
    bankId: "648f948845ca153a0334a237",
    category: "Laptop",
  },
];

export default items;
